FROM ubuntu:16.04

RUN apt update && apt upgrade -y && \
    apt install -y \
      build-essential \
      curl \
      git subversion \
      nodejs npm \
      ruby bundler \
      golang \
      rustc cargo \
      python python-pip && \
    apt clean


