FROM alpine:3.4

RUN apk add --update \
      build-base bash \
      tmux curl file nano vim \
      iproute traceroute \
      git subversion \
      nodejs \
      ruby ruby-bundler \
      go \
      python3 py-pip
